In [34]:
import numpy as np
import sys
import csv

In [31]:
def import_puzzle(i=1):
    """
    This function is to import the puzzle saved in suduku.csv
    i: the number of puzzles. range in 1 to 1,000,000.
    """
#     quizzes = np.zeros((1, 81), np.int32)
#     solutions = np.zeros((1, 81), np.int32)
    for line in enumerate(open('sudoku.csv', 'r').read().splitlines()[i:i+1]):
#         quiz, solution = line.split(",")
        quiz = line[0]
        solution = line[1]
#     quizzes = quizzes.reshape((-1, 9, 9))
#     solutions = solutions.reshape((-1, 9, 9))
    return quiz, solution

In [ ]:
i=1
for line in enumerate(open('sudoku.csv', 'r').read().splitlines()[i:i+1])

In [35]:
with open('sudoku.csv') as fd:
    reader=csv.reader(fd)
    interestingrows=[row for idx, row in enumerate(reader) if idx in (28,62)]

In [36]:
print(interestingrows)

[['900084060604005207030070080760001500053000001000409603105026090002040000800003710', '927384165684915237531672489769231548453768921218459673175826394392147856846593712'], ['507108002000043100900500006070050004100002069600700380320490000001006400009070528', '537168942286943157914527836873659214145832769692714385328495671751286493469371528']]


In [32]:
user_input = input("Please enter the number of puzzle (1-1000,000): ")
(q,s) = import_puzzle(int(user_input))
print(q)

Please enter the number of puzzle (1-1000,000): 1
0


In [37]:
with open('bigfile.csv','rb') as longishfile:
    reader=csv.reader(longishfile)
    rows=[r for r in reader]
print row[9]
print row[88]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(row[9])? (<ipython-input-37-b8da24ba85e9>, line 4)

In [42]:
with open('sudoku.csv','rt', encoding='utf-8') as longishfile:
    reader=csv.reader(longishfile)
    rows=list(reader)
print(rows[9])
# print row[88]

['503070190000006750047190600400038000950200300000010072000804001300001860086720005', '563472198219386754847195623472638519951247386638519472795864231324951867186723945']


In [41]:
with open("sudoku.csv", "rb") as infile:
    r = csv.reader(infile)
    for i in range(8): # count from 0 to 7
        next(r)     # and discard the rows
    row = next(r)   # "row" contains row number 9 now

Error: iterator should return strings, not bytes (did you open the file in text mode?)

In [28]:
def display(values):
    "Display these values as a 2-D grid."
    width = 1+max(len(values[s]) for s in squares)
    line = '+'.join(['-'*(width*3)]*3)
    for r in rows:
        print(''.join(values[r+c].center(width)+('|' if c in '36' else ''))
                      for c in cols)
        if r in 'CF': print(line)
    print

Please enter your name: 1


In [20]:
quizzes

array([[[0, 0, 4, 3, 0, 0, 2, 0, 9],
        [0, 0, 5, 0, 0, 9, 0, 0, 1],
        [0, 7, 0, 0, 6, 0, 0, 4, 3],
        [0, 0, 6, 0, 0, 2, 0, 8, 7],
        [1, 9, 0, 0, 0, 7, 4, 0, 0],
        [0, 5, 0, 0, 8, 3, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 1, 0, 5],
        [0, 0, 3, 5, 0, 8, 6, 9, 0],
        [0, 4, 2, 9, 1, 0, 3, 0, 0]],

       [[0, 4, 0, 1, 0, 0, 0, 5, 0],
        [1, 0, 7, 0, 0, 3, 9, 6, 0],
        [5, 2, 0, 0, 0, 8, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 7],
        [0, 0, 0, 9, 0, 6, 8, 0, 0],
        [8, 0, 3, 0, 5, 0, 6, 2, 0],
        [0, 9, 0, 0, 6, 0, 5, 4, 3],
        [6, 0, 0, 0, 8, 0, 7, 0, 0],
        [2, 5, 0, 0, 9, 7, 1, 0, 0]]])

In [4]:
solutions

array([[[8, 6, 4, 3, 7, 1, 2, 5, 9],
        [3, 2, 5, 8, 4, 9, 7, 6, 1],
        [9, 7, 1, 2, 6, 5, 8, 4, 3],
        [4, 3, 6, 1, 9, 2, 5, 8, 7],
        [1, 9, 8, 6, 5, 7, 4, 3, 2],
        [2, 5, 7, 4, 8, 3, 9, 1, 6],
        [6, 8, 9, 7, 3, 4, 1, 2, 5],
        [7, 1, 3, 5, 2, 8, 6, 9, 4],
        [5, 4, 2, 9, 1, 6, 3, 7, 8]],

       [[3, 4, 6, 1, 7, 9, 2, 5, 8],
        [1, 8, 7, 5, 2, 3, 9, 6, 4],
        [5, 2, 9, 6, 4, 8, 3, 7, 1],
        [9, 6, 5, 8, 3, 2, 4, 1, 7],
        [4, 7, 2, 9, 1, 6, 8, 3, 5],
        [8, 1, 3, 7, 5, 4, 6, 2, 9],
        [7, 9, 8, 2, 6, 1, 5, 4, 3],
        [6, 3, 1, 4, 8, 5, 7, 9, 2],
        [2, 5, 4, 3, 9, 7, 1, 8, 6]]])

In [5]:
quizzes[1]

array([[0, 4, 0, 1, 0, 0, 0, 5, 0],
       [1, 0, 7, 0, 0, 3, 9, 6, 0],
       [5, 2, 0, 0, 0, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 7],
       [0, 0, 0, 9, 0, 6, 8, 0, 0],
       [8, 0, 3, 0, 5, 0, 6, 2, 0],
       [0, 9, 0, 0, 6, 0, 5, 4, 3],
       [6, 0, 0, 0, 8, 0, 7, 0, 0],
       [2, 5, 0, 0, 9, 7, 1, 0, 0]])

In [ ]:
import sys

def same_row(i,j): return (i/9 == j/9)
def same_col(i,j): return (i-j) % 9 == 0
def same_block(i,j): return (i/27 == j/27 and i%9/3 == j%9/3)

def r(a):
  i = a.find('0')
  if i == -1:
    sys.exit(a)

  excluded_numbers = set()
  for j in range(81):
    if same_row(i,j) or same_col(i,j) or same_block(i,j):
      excluded_numbers.add(a[j])

  for m in '123456789':
    if m not in excluded_numbers:
      r(a[:i]+m+a[i+1:])

if __name__ == '__main__':
  if len(sys.argv) == 2 and len(sys.argv[1]) == 81:
    r(sys.argv[1])
  else:
    print 'Usage: python sudoku.py puzzle'
    print '  where puzzle is an 81 character string 
             representing the puzzle read left-to-right,
             top-to-bottom, and 0 is a blank'